### ISSUE TITLE
Usage in Vue3

### ISSUE THREAD

**Issue by lcarbonaro** [miladezzat/encrypt-rsa#14]
Trying to use this encrypt-rsa library in a Vue3 project, specifically calling it from some auth logic in a Pinia store. 

This is how I'm using the library:

``` javascript
 try {

        let myText = "whatever i need to encrypt";
        let nodeRSA = new NodeRSA();
        let pkpath = 'assets/public.key'; // also tried: path.join(__dirname, './public.key');
        let encryptedText = nodeRSA.encryptStringWithRsaPublicKey({ 
          text: myText, 
          keyPath: pkpath
        });        
        console.log('nodeRSA gives:', encryptedText );

      } catch (e) {
        console.log(e);        
      }
```

And this is the error I get: 

``` javascript
TypeError: Qc.resolve is not a function
    at e.encryptStringWithRsaPublicKey (vendor.597d2110.js:29:2388)
    at Proxy.rsaEncode (index.b3e59d3a.js:1:2951)
    at Proxy.<anonymous> (vendor.597d2110.js:5:2026)
    at Proxy.logIn (index.b3e59d3a.js:1:1300)
    at Proxy.<anonymous> (vendor.597d2110.js:5:2026)
    at d (index.b3e59d3a.js:1:4209)
    at vendor.597d2110.js:1:62460
    at Mo (vendor.597d2110.js:1:12590)
    at $n (vendor.597d2110.js:1:12669)
    at Ym (vendor.597d2110.js:1:14693)
```

Any help or insight would be appreciated.

Thanks.

**Comment by miladezzat** [comment]
Hello @lcarbonaro this module does not support frontend yet
we can add this feature if you interested to add it

**Comment by lcarbonaro** [comment]
> Hello @lcarbonaro this module does not support frontend yet we can add this feature if you interested to add it

Thanks @miladezzat . 
Perhaps you could add an encrypt method which takes the actual public key (as a string) rather than the path to the public key file ?

**Comment by miladezzat** [comment]
we can make this optional with the already exists, good idea @lcarbonaro 
Did you excited to contribute?

**Comment by miladezzat** [comment]
I will do that you didn't want

**Comment by miladezzat** [comment]
@lcarbonaro I add it for you man 😄

**Comment by lcarbonaro** [comment]
Thank you @miladezzat for the fast response and action ! 💯
