### ISSUE TITLE
nodeRSA is not defined

### ISSUE THREAD

**Issue by nk712001** [miladezzat/encrypt-rsa#28]
const { privateKey, publicKey } = nodeRSA.createPrivateAndPublicKeys();

**Comment by nk712001** [comment]
help me with this

**Comment by miladezzat** [comment]
@nk712001 
```js
import EncryptRsa from 'encrypt-rsa';

// create an instance
const nodeRSA = new EncryptRsa();

const { privateKey, publicKey } = nodeRSA.createPrivateAndPublicKeys();
```

**Comment by nk712001** [comment]
i have done it like that only but still getting this error
       TypeError: (0 , crypto_1.generateKeyPairSync) is not a function
the snippets are as follows:-
         export const nodeRSA = new NodeRSA();
         export const { privateKey, publicKey } = nodeRSA.createPrivateAndPublicKeys();

**Comment by miladezzat** [comment]
> i have done it like that only but still getting this error TypeError: (0 , crypto_1.generateKeyPairSync) is not a function the snippets are as follows:- export const nodeRSA = new NodeRSA(); export const { privateKey, publicKey } = nodeRSA.createPrivateAndPublicKeys();

what is node version you use?
