### ISSUE TITLE
TypeError: (0 , crypto_1.generateKeyPairSync) is not a function

### ISSUE THREAD

**Issue by nk712001** [miladezzat/encrypt-rsa#29]
i have done it like that only but still getting this error
TypeError: (0 , crypto_1.generateKeyPairSync) is not a function
the snippets are as follows:-
export const nodeRSA = new NodeRSA();
export const { privateKey, publicKey } = nodeRSA.createPrivateAndPublicKeys();

**Comment by nk712001** [comment]
and im using it in next js

**Comment by miladezzat** [comment]
@nk712001 what is the node version you use?

**Comment by nk712001** [comment]
@miladezzat  node = 16.19.0

**Comment by miladezzat** [comment]
> @miladezzat node = 16.19.0

will check it at this weekend

**Comment by nk712001** [comment]
any fixes available ? 
@miladezzat

**Comment by miladezzat** [comment]
@nk712001 fixed

**Comment by nk712001** [comment]
@miladezzat  thanks for the fix
