### ISSUE TITLE
Unsupported engine npm 9

### ISSUE THREAD

**Issue by pyymenta** [miladezzat/encrypt-rsa#32]
Hi there,

We have a project running using node 18 and npm 9.5.0 and we noticed that when we run `npm install`,  its shows a warning:

![image](https://user-images.githubusercontent.com/13206817/221964847-48b30e26-3670-4441-829b-30f5f993e729.png)

I realize that with the new version, 2.1.4, the engine [is compatible](https://github.com/miladezzat/encrypt-rsa/blob/master/package.json#L3) with node 18, but still uncompatible with npm 9.x:

![image](https://user-images.githubusercontent.com/13206817/221966964-10ad78b0-13a2-476f-8975-bfb49d6e7319.png)

Could we have something like this?

![image](https://user-images.githubusercontent.com/13206817/221965845-999669a9-b447-475d-9ab6-316959fe8475.png)

I think that way we provide to the clients the possibility to use the library with other versions of nodejs/npm without this warning. What do you guys think about it?

Thank you

**Comment by miladezzat** [comment]
@pyymenta fixed with the new version `2.1.5`

**Comment by pyymenta** [comment]
> @pyymenta fixed with the new version `2.1.5`

Hi @miladezzat!! Thank you very much :tada: :tada:
