### ISSUE TITLE
error in const encryptRsa = new EncryptRsa();

### ISSUE THREAD

**Issue by PrathapKaraka** [miladezzat/encrypt-rsa#34]
Compiled with problems:X

ERROR in ./node_modules/encrypt-rsa/build/index.js 37:26-43

Module not found: Error: Can't resolve 'crypto' in '/Users/prathap/Desktop/kotak/mb-admin-app-2.0/node_modules/encrypt-rsa/build'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

**Comment by miladezzat** [comment]
what is the node version and what is the framework that you use

**Comment by jet2018** [comment]
Am getting the bug with react native as the framework, any remedies. And I have crypto js already installed and working in my application

**Comment by Karmabir-Brahma** [comment]
Same error as @PrathapKaraka
Node version = 21.5.0
npm version = 10.2.5

Module not found: Error: Can't resolve 'crypto' in 'D:\Work\Major Project\Codes\MERN\client\node_modules\encrypt-rsa\build'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

**Comment by miladezzat** [comment]
To fix it on React Native
Add the following polyfill at the top of your entry file (e.g., index.js or App.js):
```ts
import 'react-native-randombytes';
import { registerRootComponent } from 'expo';
import App from './App';

if (typeof __dirname === 'undefined') {
  global.__dirname = '/';
}
if (typeof __filename === 'undefined') {
  global.__filename = '';
}

global.crypto = require('crypto');
global.Buffer = require('buffer').Buffer;

registerRootComponent(App);

```
