### ISSUE TITLE
The property name is wrong in method decryptStringWithRsaPrivateKey 

### ISSUE THREAD

**Issue by doraemone** [miladezzat/encrypt-rsa#35]
The method name and the comment mean‘s the property name should be “privateKey”.
The code is right in version 2.1.5 and became wrong from version 2.2.0.
This bug will make convertKetToBase64 throw a "Cannot read properties of undefined" error because key is undefined.

![image](https://github.com/miladezzat/encrypt-rsa/assets/7865321/e3d3fe86-2790-4e30-a372-93015a7c0cae)

**Comment by miladezzat** [comment]
@doraemone welcome to open a PR
