### ISSUE TITLE
TypeError: NodeRSA is not a constructor

### ISSUE THREAD

**Issue by eugene-qpp** [miladezzat/encrypt-rsa#40]
When using the code from instruction, with Node.js:

```
import NodeRSA from 'encrypt-rsa';

const nodeRSA = new NodeRSA();

const { publicKey, privateKey } = nodeRSA.createPrivateAndPublicKeys(1024);
```
Got the error **TypeError: NodeRSA is not a constructor**.

Also, when using with Remix at server end, got error:
**TypeError: __vite_ssr_import_2__.default is not a constructor**

When using with Remix at client end, there is no error but the publicKey and privateKey are empty.

encypt-rsa version: v3.1.1
NodeJS version: v20.16.0
Remix version: v2.11.2

**Comment by miladezzat** [comment]
fixed with new verion
