### ISSUE TITLE
Have Not Public Key

### ISSUE THREAD

**Issue by kfyidrig** [miladezzat/encrypt-rsa#8]
Hi, if I only have modulus and exponent, how can I generate the public key and encrypt it? In fact, I'm using security.js, but it can't be used in react.

security.js : http://cas.swust.edu.cn/authserver/js/security.js

**Comment by miladezzat** [comment]
Hi @kfyidrig , Sorry I don't understand you, but if you want to create a public key or private key you can do that by the following  
```
const { privateKey, publicKey } = nodeRSA.createPrivateAndPublicKeys()

// to save your keys
fs.writeFileSync('./private-key', privateKey);
fs.writeFileSync('./public-key', publicKey);
```

if you want other thing please describe it.
